#!/usr/bin/env python3

import getopt
import sys
import os

opts, args = getopt.gnu_getopt(sys.argv[1:], 'i:o:d:f:c:w:t:uh')
opts = dict(opts)

def print_usage():
    print("Usage : ugmrt2fil -i <infile> -o <outfile> -j <JNAME> -d <mjd> -f <freq> -c <nchan> -w <bandwidth> -t <sampling_time> [-u] [-h]")
    print("-i   Input file in uGMRT raw data format")
    print("-u   Output file in sigproc filterbank format")
    print("-j   JNAME of the source")
    print("-d   Timestamp in MJD")
    print("-f   Observing frequency (MHz)")
    print("-c   Number of channels")
    print("-w   Bandwidth of a single channel (MHz)")
    print("-t   Sampling time (s)")
    print("-u   Enable USB (Default is LSB)")
    print("-h   Display this help message.")

def check_req_opt(opt, desc):
    if opts.get("-"+opt) is None:
        print(desc+" is a required argument.\n")
        print_usage() 
        sys.exit(0)
    return opts.get("-"+opt)

if opts.get("-h") is not None:
    print_usage()
    sys.exit(0)
    
infile  = check_req_opt('i', "Input file")
outfile = check_req_opt('o', "Output file")
jname   = check_req_opt('j', "JNAME")
mjd     = check_req_opt('d', "Timestamp")
freq    = check_req_opt('f', "Observing frequency")
nchan   = check_req_opt('c', "No. of channels")
bw      = check_req_opt('w', "Bandwidth")
tsmpl   = check_req_opt('t', "Sampling time")
usb     = opts.get("-u") is not None


if not usb:
    print("Running ugmrt2fil for LSB.")
    headfile = os.path.basename(outfile) + ".head"
    os.system("ugmrtfilhead {} {} {} {} {} {} {} {} {}".format(infile, outfile, jname, mjd, freq, nchan, bw, tsmpl, headfile))
    os.system("cat {} {} > {}".format(headfile, infile, outfile))
    os.system("rm {}".format(headfile))
else:
    print("Running ugmrt2fil for USB.")
    os.system("ugmrtusb2fil {} {} {} {} {} {} {} {}".format(infile, outfile, jname, mjd, freq, nchan, bw, tsmpl))
    
    
    
