#!/usr/bin/env python3

"""
    Author : Abhimanyu Susobhanan
"""

import getopt
import sys
import os

opts, args = getopt.gnu_getopt(sys.argv[1:], 'i:o:j:d:f:c:w:t:B:P:uh')
opts = dict(opts)

def print_usage():
    print("Usage : ugmrt2fil -i <infile> -o <outfile> -j <JNAME> -d <mjd> -f <freq> -c <nchan> -w <bandwidth> -t <sampling_time> [-B <nbits>] [-P <npol>] [-u] [-h]")
    print("-i   Input file in uGMRT raw data format")
    print("-u   Output file in sigproc filterbank format")
    print("-j   JNAME of the source")
    print("-d   Timestamp in MJD")
    print("-f   Observing frequency (MHz)")
    print("-c   Number of channels")
    print("-w   Bandwidth of a single channel (MHz)")
    print("-t   Sampling time (s)")
    print("-u   Enable USB (Default is LSB)")
    print("-B   Number of bits (8 or 16) (Default is 16)")
    print("-P   Number of Stokes parameters (1 for Total Intensity, 4 for full Stokes) (Default is 1)")
    print("-h   Display this help message.")

def check_req_opt(opt, desc):
    if opts.get("-"+opt) is None:
        print(desc+" is a required argument.\n")
        print_usage() 
        sys.exit(0)
    return opts.get("-"+opt)

def check_default_opt(opt, desc, default, allowed):
    if opts.get("-"+opt) is None:
        print("Using default value ({}) for {}.".format(default, desc))
        return default
    elif int(opts.get("-"+opt)) not in allowed:
        print("Invalid value for "+desc)
        sys.exit(0)
    else: 
        return opts.get("-"+opt)

if opts.get("-h") is not None:
    print_usage()
    sys.exit(0)
    
infile  = check_req_opt('i', "Input file")
outfile = check_req_opt('o', "Output file")
jname   = check_req_opt('j', "JNAME")
mjd     = check_req_opt('d', "Timestamp")
freq    = check_req_opt('f', "Observing frequency")
nchan   = check_req_opt('c', "No. of channels")
bw      = check_req_opt('w', "Bandwidth")
tsmpl   = check_req_opt('t', "Sampling time")
usb     = opts.get("-u") is not None
nbit    = check_default_opt('B', "Number of bits", 16, [8,16])
npol    = check_default_opt('P', "Number of number of Stokes parameters", 1, [1,4])

if npol == 1:
    if (not usb):
        # CASE 1
        # ======
        # LSB with total intensity mode.
        # In this case, the data is already in the sigproc-filterbank format.
        # We just have to prepend the appropriate header.
        print("Running ugmrt2fil for LSB (Total Intensity).")
        headfile = os.path.basename(outfile) + ".head"
        os.system("ugmrtfilhead {} {} {} {} {} {} {} {} {} {} {}".format(infile, outfile, jname, mjd, freq, nchan, bw, tsmpl, nbit, npol, headfile))
        os.system("cat {} {} > {}".format(headfile, infile, outfile))
        os.system("rm {}".format(headfile))
    else:
        # CASE 2
        # ======
        # USB with total intensity mode.
        # Prepend header and reverse channels.
        print("Running ugmrt2fil for USB (Total Intensity).")
        os.system("ugmrtusb2fil {} {} {} {} {} {} {} {} {}".format(infile, outfile, jname, mjd, freq, nchan, bw, tsmpl, nbit))
elif npol == 4:
    # CASE 3
    # ======
    # LSB or USB with full Stokes mode.
    # Prepend header, correct the order of polarization data and reverse channels.
    # uGMRT full Stokes format :: PP PQ QQ QP
    # Format expected by dspsr :: PP QQ PQ QP
    print("Running ugmrt2fil for {} (Full Stokes).".format("USB" if usb else "LSB"))
    os.system("ugmrtstokes2fil {} {} {} {} {} {} {} {} {} {}".format(infile, outfile, jname, mjd, freq, nchan, bw, tsmpl, nbit, int(usb)))

    
    
